import type { HardwareSetupFlow } from '../../flows/hardware-setup/useHardwareSetupFlow.js';

export type ShellySetupFlow = Pick<
  HardwareSetupFlow,
  | 'acknowledgeShellyControlFeedback'
  | 'addDiscoveredSensor'
  | 'bleDiscoverySession'
  | 'bleDiscoverySnapshot'
  | 'checkShellyMutation'
  | 'recheckShellyMutation'
  | 'refreshBleDiscovery'
  | 'refreshBleDiscoveryMutation'
  | 'refreshShellyControl'
  | 'removeShellyDevice'
  | 'resetBleDiscovery'
  | 'resetShellyScan'
  | 'restartBleDiscovery'
  | 'restartBleDiscoveryMutation'
  | 'sensorDevices'
  | 'setAutomationAuto'
  | 'setAutomationManual'
  | 'setShellyDeviceName'
  | 'setShellyNameInput'
  | 'setShellyScanEndInput'
  | 'setShellyScanStartInput'
  | 'setShellyUrlInput'
  | 'setupStatus'
  | 'shellyBaseUrl'
  | 'shellyControlStates'
  | 'shellyDevices'
  | 'shellyInputState'
  | 'shellyNameInput'
  | 'shellyScanEndInput'
  | 'shellyScanMutation'
  | 'shellyScanStartInput'
  | 'shellyScanStopped'
  | 'shellyUrlInput'
  | 'startBleDiscovery'
  | 'startBleDiscoveryMutation'
  | 'startShellyScan'
  | 'stopBleDiscovery'
  | 'stopBleDiscoveryMutation'
  | 'stopShellyScan'
  | 'turnRelayOff'
  | 'turnRelayOn'
  | 'upsertShellyDevice'
>;

export type SensorSetupFlow = Pick<
  HardwareSetupFlow,
  | 'addDiscoveredSensor'
  | 'addSensorDraft'
  | 'phoneBleScanCandidates'
  | 'phoneBleScanMutation'
  | 'removeSensorDevice'
  | 'resetPhoneBleScan'
  | 'restartSavedSensorLiveScan'
  | 'sensorDevices'
  | 'sensorInputState'
  | 'sensorMacInput'
  | 'sensorNameInput'
  | 'sensorProfileInput'
  | 'sensorSamplesById'
  | 'setPvvxTimeMutation'
  | 'setSensorDeviceName'
  | 'setSensorMacInput'
  | 'setSensorNameInput'
  | 'setSensorProfileInput'
  | 'startPhoneBleScan'
  | 'startSavedSensorLiveScan'
  | 'stopPhoneBleScan'
  | 'stopSavedSensorLiveScan'
>;

export type RuleSetupFlow = Pick<
  HardwareSetupFlow,
  | 'canRunSafeRelayTest'
  | 'configState'
  | 'deleteAutomationScript'
  | 'deleteAutomationScriptMutation'
  | 'installMutation'
  | 'isAdvancedSettingsValid'
  | 'isThresholdValid'
  | 'isVpdAssistValid'
  | 'loadAutomationScript'
  | 'loadAutomationScriptMutation'
  | 'maxOnHoursInput'
  | 'minChangeMinInput'
  | 'offThresholdInput'
  | 'onThresholdInput'
  | 'rssiMinInput'
  | 'rulePreset'
  | 'safeRelayTestMutation'
  | 'selectSensorDevice'
  | 'selectShellyDevice'
  | 'selectedSensor'
  | 'selectedSensorId'
  | 'selectedShelly'
  | 'selectedShellyId'
  | 'sensorDevices'
  | 'setMaxOnHoursInput'
  | 'setMinChangeMinInput'
  | 'setOffThresholdInput'
  | 'setOnThresholdInput'
  | 'setRssiMinInput'
  | 'setRulePreset'
  | 'setStaleTimeoutMinInput'
  | 'setVpdAssistEnabled'
  | 'setVpdTargetInput'
  | 'shellyBaseUrl'
  | 'shellyDevices'
  | 'staleTimeoutMinInput'
  | 'vpdAssistEnabled'
  | 'vpdTargetInput'
>;

export type DiagnosticsSetupFlow = Pick<
  HardwareSetupFlow,
  | 'diagnosticFetchedAtMs'
  | 'diagnosticMutation'
  | 'diagnosticResourceMutation'
  | 'diagnosticResources'
  | 'diagnosticShelly'
  | 'diagnosticShellyId'
  | 'diagnosticSnapshot'
  | 'refreshDiagnostics'
  | 'setDiagnosticShellyId'
  | 'shellyDevices'
>;

export type TimeScheduleSetupFlow = Pick<HardwareSetupFlow, 'selectedShelly'>;
