import type { HardwareSetupFlow } from '../../flows/hardware-setup/useHardwareSetupFlow.js';
import type { SensorManagementFlow } from '../../flows/devices/sensors/useSensorManagementFlow.js';

export type ShellySetupFlow = Pick<
  HardwareSetupFlow,
  | 'acknowledgeShellyControlFeedback'
  | 'addDiscoveredSensor'
  | 'bleDiscoverySession'
  | 'bleDiscoverySnapshot'
  | 'checkShellyMutation'
  | 'recheckShellyMutation'
  | 'refreshBleDiscovery'
  | 'refreshBleDiscoveryMutation'
  | 'refreshShellyControl'
  | 'removeShellyDevice'
  | 'resetBleDiscovery'
  | 'resetShellyScan'
  | 'restartBleDiscovery'
  | 'restartBleDiscoveryMutation'
  | 'sensorDevices'
  | 'setAutomationAuto'
  | 'setAutomationManual'
  | 'setShellyDeviceName'
  | 'setShellyNameInput'
  | 'setShellyScanEndInput'
  | 'setShellyScanStartInput'
  | 'setShellyUrlInput'
  | 'setupStatus'
  | 'shellyBaseUrl'
  | 'shellyControlStates'
  | 'shellyDevices'
  | 'shellyInputState'
  | 'shellyNameInput'
  | 'shellyScanEndInput'
  | 'shellyScanMutation'
  | 'shellyScanStartInput'
  | 'shellyScanStopped'
  | 'shellyUrlInput'
  | 'startBleDiscovery'
  | 'startBleDiscoveryMutation'
  | 'startShellyScan'
  | 'stopBleDiscovery'
  | 'stopBleDiscoveryMutation'
  | 'stopShellyScan'
  | 'turnRelayOff'
  | 'turnRelayOn'
  | 'upsertShellyDevice'
>;

export type SensorSetupFlow = SensorManagementFlow;

export type RuleSetupFlow = Pick<
  HardwareSetupFlow,
  | 'canRunSafeRelayTest'
  | 'configState'
  | 'deleteAutomationScript'
  | 'deleteAutomationScriptMutation'
  | 'installMutation'
  | 'isAdvancedSettingsValid'
  | 'isThresholdValid'
  | 'isVpdAssistValid'
  | 'loadAutomationScript'
  | 'loadAutomationScriptMutation'
  | 'maxOnHoursInput'
  | 'minChangeMinInput'
  | 'offThresholdInput'
  | 'onThresholdInput'
  | 'rssiMinInput'
  | 'rulePreset'
  | 'safeRelayTestMutation'
  | 'selectSensorDevice'
  | 'selectShellyDevice'
  | 'selectedSensor'
  | 'selectedSensorId'
  | 'selectedShelly'
  | 'selectedShellyId'
  | 'sensorDevices'
  | 'setMaxOnHoursInput'
  | 'setMinChangeMinInput'
  | 'setOffThresholdInput'
  | 'setOnThresholdInput'
  | 'setRssiMinInput'
  | 'setRulePreset'
  | 'setStaleTimeoutMinInput'
  | 'setVpdAssistEnabled'
  | 'setVpdTargetInput'
  | 'shellyBaseUrl'
  | 'shellyDevices'
  | 'staleTimeoutMinInput'
  | 'vpdAssistEnabled'
  | 'vpdTargetInput'
>;

export type DiagnosticsSetupFlow = Pick<
  HardwareSetupFlow,
  | 'diagnosticFetchedAtMs'
  | 'diagnosticMutation'
  | 'diagnosticResourceMutation'
  | 'diagnosticResources'
  | 'diagnosticShelly'
  | 'diagnosticShellyId'
  | 'diagnosticSnapshot'
  | 'refreshDiagnostics'
  | 'setDiagnosticShellyId'
  | 'shellyDevices'
>;

export type TimeScheduleSetupFlow = Pick<HardwareSetupFlow, 'selectedShelly'>;
