from pathlib import Path


def replace(path: str, old: str, new: str, count: int = 1) -> None:
    p = Path(path)
    text = p.read_text(encoding='utf-8')
    if old not in text:
        raise SystemExit(f'pattern not found in {path}: {old[:180]!r}')
    p.write_text(text.replace(old, new, count), encoding='utf-8')


hw = 'apps/mobile/src/__tests__/hardware-setup.test.tsx'

# Add a stable navigation helper; page labels vary by locale/context, the shared class does not.
anchor = """const openRuleScriptDialog = async () => {
  openRuleDeveloperTools();
  fireEvent.click(screen.getByRole('button', { name: 'Podgląd Shelly Script' }));
  return screen.findByRole('dialog', { name: 'Podgląd Shelly Script' });
};
"""
addition = anchor + """
const closeCurrentAddPage = () => {
  const back = document.querySelector<HTMLButtonElement>(
    '.app-page-back-row .setup-context__back'
  );
  expect(back).not.toBeNull();
  fireEvent.click(back!);
};
"""
replace(hw, anchor, addition)

replace(
    hw,
    """  fireEvent.click(within(addDialog).getByRole('button', { name: 'Dodaj' }));
  expect(await screen.findByText('Dodano gniazdko.')).toBeInTheDocument();
  expect(
    screen.queryByRole('dialog', { name: 'Dodaj gniazdko' })
  ).not.toBeInTheDocument();
  expect(screen.getByRole('button', { name: 'Ustawienia gniazdka' })).toBeInTheDocument();""",
    """  fireEvent.click(within(addDialog).getByRole('button', { name: 'Dodaj' }));
  expect(await screen.findByRole('button', { name: 'Ustawienia gniazdka' })).toBeInTheDocument();
  expect(screen.queryByRole('dialog', { name: 'Dodaj gniazdko' })).toBeNull();
  expect(screen.queryByRole('heading', { name: 'Dodaj gniazdko' })).toBeNull();""",
)

replace(
    hw,
    """  fireEvent.click(within(addDialog).getByRole('button', { name: 'Dodaj' }));
  expect(
    screen.queryByRole('dialog', { name: 'Dodaj termometr' })
  ).not.toBeInTheDocument();""",
    """  fireEvent.click(within(addDialog).getByRole('button', { name: 'Dodaj' }));
  expect(await screen.findByText(name)).toBeInTheDocument();
  expect(screen.queryByRole('dialog', { name: 'Dodaj termometr' })).toBeNull();
  expect(screen.queryByRole('heading', { name: 'Dodaj termometr' })).toBeNull();""",
)

# The architectural test generated by v115 returns through the shared page Back control.
replace(
    hw,
    """    expect(screen.queryByRole('dialog', { name: 'Dodaj gniazdko' })).toBeNull();
    fireEvent.click(screen.getByRole('button', { name: 'Shelly' }));

    fireEvent.click(screen.getByRole('button', { name: 'Termometry' }));""",
    """    expect(screen.queryByRole('dialog', { name: 'Dodaj gniazdko' })).toBeNull();
    closeCurrentAddPage();

    fireEvent.click(screen.getByRole('button', { name: 'Termometry' }));""",
)

# Tests that used a modal close button now navigate back from the child page.
replace(
    hw,
    "    fireEvent.click(within(addDialog).getByRole('button', { name: 'Zamknij' }));",
    "    closeCurrentAddPage();",
    count=2,
)
replace(
    hw,
    "    fireEvent.click(within(addSensorDialog).getByRole('button', { name: 'Zamknij' }));",
    "    closeCurrentAddPage();",
)

nav = 'apps/mobile/src/__tests__/navigation-settings-regression.test.tsx'
replace(
    nav,
    """    fireEvent.click(screen.getByRole('button', { name: 'Anuluj' }));
    expect(screen.getByRole('heading', { name: 'dashboard-test' })).toBeVisible();""",
    """    const back = document.querySelector<HTMLButtonElement>(
      '.app-page-back-row .setup-context__back'
    );
    expect(back).not.toBeNull();
    fireEvent.click(back!);
    expect(screen.getByRole('heading', { name: 'dashboard-test' })).toBeVisible();""",
)

print('Child-page navigation tests aligned')
