from pathlib import Path

path = Path('apps/mobile/src/__tests__/hardware-setup.test.tsx')
text = path.read_text()
marker = "  it('keeps standalone device-add pages free of duplicate top navigation and titles', () => {\n"
insert = """  it('opens saved Shelly settings and BLE discovery as nested child pages', async () => {\n    useHardwareSetupDraftStore.getState().upsertShellyDevice({\n      id: 'http://192.168.0.20/',\n      name: 'Salon',\n      baseUrl: 'http://192.168.0.20/',\n      scriptIdInput: '1'\n    });\n    vi.stubGlobal(\n      'fetch',\n      vi.fn(async (_input: RequestInfo | URL, init?: RequestInit) => {\n        const { method } = requestBody(init);\n        if (method === 'Shelly.GetDeviceInfo') {\n          return rpcResult({ id: 'shellyplugsg3-pages', model: 'S3PL-00112EU', gen: 3 });\n        }\n        if (method === 'Shelly.GetStatus') {\n          return rpcResult({\n            matter: { enabled: false },\n            script: { enable: true },\n            ble: { enable: true },\n            'switch:0': { id: 0, output: false },\n            wifi: { rssi: -55 },\n            sys: { time: '12:00', unixtime: 1_800_000_000, uptime: 3600 }\n          });\n        }\n        if (method === 'Script.List') return rpcResult({ scripts: [] });\n        return rpcResult({});\n      })\n    );\n\n    renderHardwareSetup({ setupIntent: 'temperature', onBackToIntent: vi.fn() });\n    fireEvent.click(screen.getByRole('button', { name: 'Ustawienia gniazdka' }));\n\n    expect(screen.queryByRole('dialog', { name: 'Salon' })).toBeNull();\n    expect(await screen.findByRole('heading', { name: 'Salon' })).toBeVisible();\n    expect(screen.getByRole('button', { name: '‹ Shelly' })).toBeVisible();\n    expect(screen.queryByRole('navigation', { name: 'Menu konfiguracji' })).toBeNull();\n\n    fireEvent.click(\n      screen.getByRole('button', { name: 'Skanuj termometry BLE przez to gniazdko' })\n    );\n    expect(screen.queryByRole('dialog', { name: 'Skanuj termometry BLE' })).toBeNull();\n    expect(\n      await screen.findByRole('heading', { name: 'Skanuj termometry BLE' })\n    ).toBeVisible();\n    expect(screen.getByRole('button', { name: '‹ Salon' })).toBeVisible();\n    expect(screen.queryByRole('navigation', { name: 'Menu konfiguracji' })).toBeNull();\n\n    fireEvent.click(screen.getByRole('button', { name: '‹ Salon' }));\n    expect(await screen.findByRole('heading', { name: 'Salon' })).toBeVisible();\n    expect(screen.queryByRole('dialog')).toBeNull();\n\n    fireEvent.click(screen.getByRole('button', { name: '‹ Shelly' }));\n    expect(screen.getByRole('navigation', { name: 'Menu konfiguracji' })).toBeVisible();\n    expect(screen.getByRole('button', { name: 'Ustawienia gniazdka' })).toBeVisible();\n  });\n\n"""
if marker not in text:
    raise SystemExit('configurator Shelly child-page test insertion marker not found')
path.write_text(text.replace(marker, insert + marker, 1))
print('Configurator Shelly child-page regression test patched')
